version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 30 sh -c "until docker info; do echo .; sleep 1; done"

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Paketo image...
      - pack build ebpr-address-base-updater-image --builder paketobuildpacks/ubuntu-noble-builder
      # Ensure node and npm is available on the entrypoint
      - docker run -it --rm --entrypoint launcher ebpr-address-base-updater-image npm --version

  post_build:
    commands:
      - echo Build completed on `date`
      - docker save -o ebpr-address-base-updater-image.tar ebpr-address-base-updater-image:latest

artifacts:
  files:
    - '**/*'
